### PR TITLE
Feature/optimalpca

### PR DESCRIPTION
**Pull request by stanleyjs**
I updated the thresholding to follow the optimality conditions derived by Gavish and Donoho [here](https://arxiv.org/abs/1305.5870 ).

This required adding a marcenkopastur median function to the package.  I stuck it in utils, which is where I propose general mathematics classes go.

I'd like to clean up the interface for PCA and low rank approximation more at some point, but for now I extracted `_reduce_data` into another static class `LowRankApproximation` which has methods for computing the optimal svd thresholds. Other methods for this type of stuff should land here.

Added `n_iters` to the pca interface, which basically is there for debug as otherwise you can get very divergent approximations through random svd.

There are tests for all of the new updates.

Also, I noticed that we're failing a few tests for matching graphs.   Looks like some tolerance issues.I did not fix.

### CODE REVIEW

**Comment by stanleyjs** [comment]
A couple things:  The previous implementation of rank thresholding was just based on the numerical rank, which appears to be the wrong thing to look at, at least according to donoho.  You'd end up taking way too many PCs.  This estimator actually appears to do quite well and take only a few.

The other thing is that before we had to compute the whole spectrum.  Now we can just compute the first `k0 = ceil(min(X.shape)/2) ` singular values and threshold from there.  This is way faster. `sigma_k0 is = median(singularvalues(X))`

A last observation is that the cutoff `threshold` is effectively always going to be  `threshold > 1.5 * sigma_k0`.  You can get this using `beta = m/n` where `m = min(X.shape)`, `n = max(X.shape)`,  and referencing table 4 in the above paper.  It may creep down below 1.5 when `0<beta << 0.05` but that is a regime we will hardly ever see.

That would seem to imply that if we could estimate `sigma_k0` quickly, then we could estimate how many singular values are above the threshold, i.e. `k1 = sum(sigma>threshold)` and compute the final truncated SVD only to k1 without ever doing any full compute to `k0` and then trimming. Since we know `k0` by virtue of it being the median , the work is really just to borrow someone's singular value estimator such as the ones used in the matlab version of gspbox.  I think there is an implementation discussed in the compressive spectral clustering papers too.

**Comment by stanleyjs** [comment]
@dburkhardt @scottgigante I am interested to see if this new estimator recovers n_pca close to what you would choose on your own curated datasets. 

If I can port over the fast estimates of the k-th singular value mentioned above, then you'd have very low overhead automatic selection.  Right now it is on the order of whatever it takes to compute the SVD to the `k= min(m,n)/2` singular vector, which isn't slow but it's not as fast as just defaulting a low standard value such as `k=100`. The bottleneck is just that the randomized svd requires an iterative compute rather than grabbing particular sigmas. 

The mathematics seem very solid and combining the new implementation with fast sigma_k estimation effectively removes a parameter from any algorithm that depends on dimensionality reduction via PCA.

**Comment by scottgigante** [comment]
I haven't reviewed the code yet, but I just reran CI on `dev` and all tests are passing, so whatever tolerance issues exist it appears they were introduced by this change. I'll get to reviewing the code soon.

**Comment by scottgigante** [comment]
Also I'm not sure this usage of static methods is particularly elegant. Why should this be a class if it is never instantiated? And moreover, why shouldn't these methods be attached to `Data`?

**Comment by stanleyjs** [comment]
@scottgigante I just reran `nose2` on `dev` and it failed `test_knnmax`.

The other bug is due to randomized svd producing non uniform results because it is random.  I changed some parameters to default to sklearn 'auto' for dense PCA and it works now.

As far as the static classing goes, I don't think elegance is a particularly relevant criticism.  We're not designing dresses here.  But I will address a few things.

1) `Data` contains data and points to objects (like `data_pca => sklearn.truncatedsvd`), but I don't think it is particularly elegant to shoe horn a family of methods into `data` that are tangientally related.  A slippery slope argument: If PCA is a dimensionality reduction method, then why don't we shove all dimensionality reduction methods into `data`?  From an organizational perspective it is really not elegant to cram a bunch of methods from disparate papers and implementations into one worker class.  

2) The `marcenkopastur` methods and the associated estimator must stay static to avoid scope games and for clarity.  They are minimal mathematical methods that don't really require a set of attributes to compute, and their state/flow doesn't change dynamically.  I don't that it is organizationally elegant to push out these methods into module level functions either.  It makes sense to file them in the same class name.

3) Ultimately I think that `LowRankApproximation` is more useful and versatile by being able to be called on any data matrix input without entering into the whole graphtools data api.  I also don't think that there is anything there worth copying and/or muting over time after you have run PCA once.  

Now that I think about it, one could actually subclass `LowRankApproximation` with a `PCA` subclass and an actual `LRA` subclass that does full-fledged LRA. In the long term you'd then have a property `Data(X). LRA` that stores and returns an LRA of `X`, and `Data(X).PCA`, etc...

**Comment by scottgigante** [comment]
I agree that we shouldn't cram everything into one class, but I don't see any reason for these things to be a class at all - seems more like a submodule to me.

Re: our offline discussions on this potentially breaking out into a separate module, would you like to do that in the short term or shall we still include it here for now?

**Comment by scottgigante** [comment]
@stanleyjs tests are passing. You just need to fix your formatting: https://github.com/KrishnaswamyLab/graphtools/blob/master/CONTRIBUTING.md#code-style-and-testing

**Comment by stanleyjs** [comment]
Let's table for now and push this into `pypca`

**Pull request closed without merging**
